version: '3'

services:
  chatservice:
    build: .
    container_name: chatservice
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
      - "50052:50051"

  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat_test
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgres
