version: '3'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat-test
    ports:
      - "3306:3306"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
