// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package db

import (
	"context"
	"time"
)

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (id, user_id, initial_message, status, token_usage, model, model_max_tokens, temperature, stop, max_tokens, presence_penalty, frequency_penalty, created_at, updated_at) 
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateChatParams struct {
	ID               string
	UserID           string
	InitialMessage   string
	Status           string
	TokenUsage       int16
	Model            string
	ModelMaxTokens   int16
	Temperature      string
	Stop             string
	MaxTokens        int16
	PresencePenalty  string
	FrequencyPenalty string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.ExecContext(ctx, createChat,
		arg.ID,
		arg.UserID,
		arg.InitialMessage,
		arg.Status,
		arg.TokenUsage,
		arg.Model,
		arg.ModelMaxTokens,
		arg.Temperature,
		arg.Stop,
		arg.MaxTokens,
		arg.PresencePenalty,
		arg.FrequencyPenalty,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findChatByID = `-- name: FindChatByID :one
SELECT id, user_id, initial_message, status, token_usage, model, model_max_tokens, temperature, top_p, n, stop, max_tokens, presence_penalty, frequency_penalty, created_at, updated_at FROM chats WHERE id = ?
`

func (q *Queries) FindChatByID(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, findChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InitialMessage,
		&i.Status,
		&i.TokenUsage,
		&i.Model,
		&i.ModelMaxTokens,
		&i.Temperature,
		&i.TopP,
		&i.N,
		&i.Stop,
		&i.MaxTokens,
		&i.PresencePenalty,
		&i.FrequencyPenalty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
